language: node_js
node_js:
  - 4.1
install: "npm i -g mocha babel && npm i"

deploy:
  - provider: npm
    on:
      tags: true
    email:
      secure: "KxE9AjYULgbFsXfAlo3ECT841v8fIXVspvZ4ElDPtYIdAYI8W0zngs3l0GGWnB3h9ecpJhLdFPRvvmYiIVcZW5k1e5sRV6SNkLoOcUvkkPDTnAtD2+PLd9gEZ8wiUWUTqm6J33scjgSn3aLTsM9LtH3/JmyRqthfvkr8uLkfCgkcuGSD3WBPqWuOy/roo7W4duy4jzt0mQXIXc7D2pIFQbVmxbSzU/wSvIqsXgb2O8FyYFBQ3K4h2KD6d6ONHaf1bGtMlhMosYu9j7cl6e0K+AWqIiNhdGfU+R7kIV6qYM/s5+bed4aTSiJM0bwWhN7ffMa2FP7/gUB/5UW3dZO6vrszwO2LVafVzmAAAw8grujGNpu8a/T2DMTcxmdCT0gK6QEkaJSH4lIfB8MKiw2nSBmLiKZezIkSp5tb4naC4rf5y8TzLeWBGcEflxxQPnuQJbFsQDb7yT7iLfu+5lRd+utgTlb2sM2Wz4OfFbk9VzDBnCg1JIxZxiyYaMYzpDRprvaVt6V/dHVuE1YjZDwZ5YTx77KbUfwGjC9KnPYuqoQHxKHjnOLqSHBR2/VN8sRoZJGk3tdilW8bRBQX/4kynE7wBkCYavZCekR5Socryed3ClfQ+RnRYBbLcrkGgQZro5qXgQHumfdZVs5gPQoEa6jGzCyhl1GH6B7tEGjhuNg="
    api_key:
      secure: "KHAe0HbDxEflOMtQd9nVKUUu9pRq3Cyf6+x+DCl1ixTWLXCYVi670B/RYzK/a7SBkE6g3O2Cv4SKDSL3T03uRjlTqlZfDl4Kyr5RGyLBd1KfeG935GSADBdh/KJrwbNzOCL6bD+sRBe9pMuVXr5Fei5n2aFHeJPm8UG4lZq0xVtiW4/yhygvOuSULsMLLzZa+xx9uV+0DutrDDYidxsQnH6CtncUbDgGUIZyGt0WfX1Edh8uNuSOhyRWbRZ0znJWKMijOQX9+Fx75C/mYV4Gtur9t8PHE2biRhrEJzzf5aBOpqqJRFfSbp0N6rzJrCX3Z8kkRNPy9oMiFy1nFgCEZ3RX57s9ZL+eyZPd1R7OY8kA3ZIy/Ck2JkDryDpOzazyLmVVJWep2vzUu+coPBULIYA+2pLAH8ncYNEAa3alKG1kGomVEddBPnXwbu8jLH8zm8SojLOrJh/eliz7nDhHOJa8ZP2u/Mk03LK6w/jTcL1x/U8YDNbX7FQOSCwNXYsBqyoI5OTNuuItBbDiB6xoq5AmJWdwvYFPACtEiePaXrxP/0WipM1VResb/EdfzVNE6Ot93xC10SiQjdRgf5HozvB9J4n0MCuiu9uSx7XOxbUZ4mGAEAC7UWRQsGsFQ9FyI7zI2jr/zTYcbXAYMNLfMyIt0EZzepWMMUKGX1SRklU="
    skip_cleanup: true